use_frameworks!

platform :ios, '9.0'

target 'HHSwipeCollectionViewCell_Example' do
  pod 'HHSwipeCollectionViewCell', :path => '../'

  target 'HHSwipeCollectionViewCell_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
